### ISSUE TITLE
Imbalance question

### ISSUE THREAD

**Issue by jfreds91** [lewisbails/cem#3]
* cem version: n/a
* Python version: n/a
* Operating System: n/a

### Description

Hi! I have a question about CEM, in particular, the measure of imbalance. It may be indicative of a bug, but more likely it's just my misinterpretation :)

My question is: after weighting, if we sum the relative frequency of the treated and control units scaled by their respective weights, wouldn't we expect the imbalance metric to be 0? I believe the weighting accounts exactly for that. In your documentation you show that it comes out to 0.6 for an example case; in a toy example of my own (modified such that matching features are explicitly called out, otherwise the same) it came out close to 0. In the original [paper](https://gking.harvard.edu/files/political_analysis-2011-iacus-pan_mpr013.pdf), I haven't been able to find an imbalance equation with weights applied.

This is the line of interest in the code: [link](https://github.com/lewisbails/cem/blob/66f5e796f1fdce39c1ebc7247c7943efa9f855e1/cem/imbalance.py#L47)

Your insight here would be greatly appreciated, thanks!

**Comment by lewisbails** [comment]
Hi @jfreds91 
The imbalance at the chosen level of coarsening should indeed be 0 after pruning and weighting. But the imbalance shown is calculated using the pre-calculated coarsening schema (see CEM.__init__). The pre-calculated schema is intended to be used to compare several schema, which would otherwise yield imbalance of 0 at their respective levels of coarsening.
